### ISSUE TITLE
Show editor buttons by default

### ISSUE THREAD

**Issue by brylie** [JackAdams/meteor-editable-text-wysiwyg-bootstrap-3#2]
From the demo application, it seems that the rich text buttons are initially hidden until clicking an expand arrow on the toolbar. Is there a configuration to show the rich text editor buttons by default?

**Comment by JackAdams** [comment]
Not yet, but that shouldn't be hard to implement.  Good idea.

**Comment by Rahbaran** [comment]
+1 for this idea. That was the first thing I encountered that I would like to change. Maybe less tech-savvy people wouldn't see the arrow to expand the editor.

**Comment by JackAdams** [comment]
Yes, this feature is coming in a few weeks.  Just a bit swamped with other stuff at the moment.

**Comment by brylie** [comment]
@JackAdams is there any way I can help with this task? For example, I can do some basic JavaScript work, if you can offer guidance.

**Comment by JackAdams** [comment]
@brylie thank you for the offer.  It would take longer for me to explain than to make the change myself (it's about a 10 minute job).  I just need to find 10 minutes in a pretty hectic time of year.  I'll try to release a new version tonight.

**Comment by JackAdams** [comment]
Just released a version with parameter `showToolbar=true` available to do this.

**Comment by brylie** [comment]
Thanks @JackAdams. By the way, are you considering setting up an account on Gratipay?
https://gratipay.com/on/github/JackAdams/

**Comment by JackAdams** [comment]
@brylie I'm just happy if my packages save other developers some time. There are thousands of development hours worth of FOSS that I use in my projects, for which I'm exceedingly grateful.
