### ISSUE TITLE
Move editor buttons to header

### ISSUE THREAD

**Issue by brylie** [JackAdams/meteor-editable-text-wysiwyg-bootstrap-3#3]
From the demonstration application, it seems like the editor buttons appear below the rich text area. Is there a configuration option to display the editor toolbar above the rich text area?

**Comment by JackAdams** [comment]
Yes, there's a bunch of undocumented options and that's one of them.  When you initialize the widget, write:

```
{{> editbleText collection="collectionName" field="fieldName" wysiwyg=true toolbarPosition="top"}}
```
