### ISSUE TITLE
Editable text widget is unusable if the document is empty

### ISSUE THREAD

**Issue by tlau** [JackAdams/meteor-editable-text-wysiwyg-bootstrap-3#5]
When you get started with the editable text widget on a new collection the first document is empty. This renders nothing on the page that can be clicked to activate the wysiwyg widget to add text to it.

Is there any way to configure it to have placeholder text or some kind of indication that the widget is there?  I can't even find a place to click on it, it seems to not generate any clickable space on the page to interact with.

**Comment by tlau** [comment]
Sample app showing this behavior: http://meteorpad.com/pad/GKiMvvKWCTMnni6Qg/EditableTest

**Comment by JackAdams** [comment]
When you put the widget in the html, use a `substitute` param, e.g.:

```
 {{> editableText collection="posts" field="body" wysiwyg=true acceptEmpty=true substitute='<i class="fa fa-pencil"></i>'}}
```

Alternatively, if you add `class="editable-text-trigger"` to the enclosing html tag, clicking that tag will trigger the editing.

p.s. Big props for putting a repro up on Meteorpad!! Thanks.

**Comment by tlau** [comment]
The substitute param doesn't seem to do anything: http://meteorpad.com/pad/mmcdrZi7ZE7x5hXNd/Copy%20of%20EditableTest

**Comment by JackAdams** [comment]
Take a look a the code here: 
http://meteorpad.com/pad/mRkhmMgnCaRfRKKZS/Copy%20of%20Editable%20Test%202
`babrahams:wysiwyg` doesn't do anything by itself -- it's a dependency of `babrahams:editable-text-wysiwyg-bootstrap-3`.
Also, you need to give the widget a non-null context.  That's why there was an error in the console.

**Comment by tlau** [comment]
Got it. I think the console error happens when Meteor first loads the page, before subscriptions are loaded.

**Comment by JackAdams** [comment]
True. I just made a little tweak to the [meteorpad test app](http://meteorpad.com/pad/mRkhmMgnCaRfRKKZS/Copy%20of%20Editable%20Test%202) that should fix that.

**Comment by tlau** [comment]
Cool, thanks for the help!
