### ISSUE TITLE
& is converted to &amp;

### ISSUE THREAD

**Issue by t3db0t** [JackAdams/meteor-editable-text-wysiwyg-bootstrap-3#6]
When I put in an `&` in an editableText field, it gets set in the database as `&amp;`.

I've checked through the documentation but I don't see anything that I'm specifically doing wrong here; I'm not setting `trustHtml` or any other custom configuration.  I'm doing:

`{{> editableText collection="meetings" field="name" inputClass="meetingNameInput"}}`

And that's it.  Is there something else I need to do?

**Comment by JackAdams** [comment]
I'll have a look into it and get back to you as soon as possible.

**Comment by JackAdams** [comment]
The latest version of the package should not change `&` to `&amp;` unless you have `wysiwyg=true` as a parameter.

Anything from a rich text editor is put through the `sanitizeHtml` package which escapes html entities before it puts them in the database.

**Comment by t3db0t** [comment]
Hm, I just upgraded from 0.3.14 to 0.3.19, but I don't see any change on this issue.  I am not using `wysiwyg=true`.  Anything else I could check?

**Comment by JackAdams** [comment]
I can't reproduce this at the moment.  Is there any chance you could put a minimal repro on meteorpad?

This issue was (in theory) fixed somewhere between 0.3.14 and 0.3.19.

**Comment by t3db0t** [comment]
I tried to reproduce this with a minimal setup but it worked as expected!  So I'll have to do some more digging in my app and see what the problem is...

**Comment by t3db0t** [comment]
Finally fixed—it turns out my packages were not updating with `meteor update`.  I had to `meteor remove` and then re-add.  Weird.
